### PR TITLE
(GH-80) existing icons will be honored

### LINKED ISSUE #80: Honor existing icon
When I added the guidelines package to my addin, it created a new icon file and directed me to change the project properties to use this new icon despite the fact that my addin already uses the cake-contrib icon but with a different name.

Is it possible to honor the existing icon?

If so, maybe check the binary content of the existing icon and compare it with the binary content of the cake-contrib icon to ensure the author is using the desired png file.

### PR DESCRIPTION
**Pull request by nils-a**
Additionally no local copy of the icon is needed anymore.

The setting $(CakeContribGuidelinesIconDestinationLocation) has
been removed. Any old build/project using this setting will now fail.

fixes #80 

## What has changed

Activate this on a project with **no** `PackageIcon`-property, no referenced icon:
You'll get the default icon as `icon.png` in the nupkg, automatically. No files added to the project.

Activate this on a project with `PackageIcon` set to some arbitrary `png` (e.g. `<PackageIcon>my-cool-icon.png</PackageIcon>`), but **no** referenced icon:
You'll get the default icon renamed (e.g. to `my-cool-icon.png` in the nupkg. Still, no files added to the project.

Activate this on a project with `PackageIcon` and a corresponding referenced icon (probably the default for all existing packages):
On build the icon will be checked and overridden/updated, if needed.

### Additionally:

* `PackageIconUrl` will automatically be set to `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png` if not specified
* `CakeContribGuidelinesIconDestinationLocation` was removed. This is a **breaking change**.

### CODE REVIEW

**Comment by Jericho** [comment]
Automatically setting the `PackageIconUrl` is a very nice touch.

**Comment by nils-a** [comment]
@Jericho They are published "here" in GitHub, however not for PRs. Interestingly though, Currently there was not even a nupkg uploaded as an artifact in this build.

**Comment by Jericho** [comment]
I just used `CakeContrib.Guidelines.0.6.0-gh-80-0001.nupkg` on two of my addins:
- it honored my embedded icon icon in both cases, which is great
- it did not complain about the fact that neither of my csproj contain `PackageIconUrl`
- in one case it, the project is targeting netstandard2.0 ONLY and it complained that I am missing net461
image
- in the other case, which is also targeting netstandard2.0 ONLY, it complained that I am missing  net461 and net5.0
image

**Comment by nils-a** [comment]
The difference in the `CCG0007` warning is probably a regression from #99 - I'll debug that on the two examples.

That the rest worked for you I'll take as a :shipit:

**Comment by Jericho** [comment]
Why are the targeting rules different depending on whether an addin targets Cake.Core or not? Shouldn't we be consistent and always make the same recommendation?

Also, did you see my comment about that fact that my csproj is missing `PackageIconUrl` but I did not get a warning? I was under the impression that it would be automatically set.

**Comment by nils-a** [comment]
@Jericho 
>  did you see my comment about that fact that my csproj is missing PackageIconUrl but I did not get a warning?

I did, sorry for not commenting on that. When no `PackageIconUrl` is set, it will be automatically set to  `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png` - there will be no warning generated. 

>Why are the targeting rules different depending on whether an addin targets Cake.Core or not?

The rules are "follow" the Cake version: If you are targeting Cake ≥ 1.0.0 the "requirement" is for `netstandard2.0` and suggestions (i.e. warnings) are for `net461` and `net5.0`. If you target Cake < 1.0.0, the `net5.0` is not suggested because Cake can not handle that.

Now, the question arises what to do in cases where no reference to `Cake.Core` or `Cake.Common` is set. Currently the rule defaults to the "lowest" requirement - in this case that is the "Cake < 1.0.0"-rule. 
We could argue, that since Cake 1.0.0 is now the default, the default-rule should be the "Cake ≥ 1.0.0"-rule.

**Comment by Jericho** [comment]
>  When no `PackageIconUrl` is set, it will be automatically set to `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png` - there will be no warning generated.

This did not work as expected:  the value was not automatically set for either of my two addins.

**Comment by nils-a** [comment]
You are right. Additionally I see two icons packed when packing `Cake.Email.Common`. Will analyze that.

**Comment by nils-a** [comment]
The "two icons" being packed was me using a wrong nupkg.
The `PackageIconUrl` not being set has been fixed.

**Pull request merged**
